### ISSUE TITLE
Fix pdf (not showing plots images)

### ISSUE THREAD

**Issue by sabaferdous12** [LearnToDiscover/sandpaper#20]
At the moment, any plot originating from python code are not being displayed in the pdf. This is due to md file contains html tag for image while Pandoc only reads image tag. 

e.g: 

```html
<    img src="fig/01-data_frames_1-rendered-unnamed-chunk-35-3.png" width="672" style="display: block; margin: auto;" />
```
 
but workable line is:

```md
!  [] (fig/01-data_frames_1-rendered-unnamed-chunk-34-1.png)
```

We need to fix this in sandpaper

**Comment by milanmlft** [comment]
As a side note: the problem is not only for **Python-generated figures**, but for _any_ code-generated figures.
A minimal example can be found here: [milanmlft/tmp-lesson-figs at 3ad21412053828ea64698e3b04145b71b674ad29](https://github.com/milanmlft/tmp-lesson-figs/tree/3ad21412053828ea64698e3b04145b71b674ad29)

The generated pdf: [introduction.md.pdf](https://github.com/LearnToDiscover/sandpaper/files/11601778/introduction.md.pdf)

**Comment by milanmlft** [comment]
[chrome_print function - RDocumentation](https://www.rdocumentation.org/packages/pagedown/versions/0.20/topics/chrome_print) might be useful

This would require installing Chromium on the GHA runners, for which [browser-actions/setup-chrome: Set up your GitHub Actions workflow with a specific version of chromium](https://github.com/browser-actions/setup-chrome) might be used
