### ISSUE TITLE
Create L2D handbook

### ISSUE THREAD

**Issue by L2D-admin** [LearnToDiscover/sandpaper#73]
Under the 'learner profiles' we can add, for instance, a single set of instructions for students on how to do a single thing. For example, using terminal for x, y or z. Is it possible to have multiple 'files' or sets of instructions here? So if we wanted to add a second set of instructions on how to set up a Codespace, for example: is this an option? Thank you!

**Comment by milanmlft** [comment]
Yes, this is possible, see for example https://github.com/carpentries/sandpaper-docs/tree/main/learners
For which the rendered website looks like this:

<img width="450" alt="Screenshot 2024-05-30 at 15 36 51" src="https://github.com/LearnToDiscover/sandpaper/assets/38256462/dae4453b-05aa-434c-a138-f823a6344ff1">

See also [the sandpaper documentation](https://carpentries.github.io/sandpaper-docs/editing.html#folder-structure)

**Comment by sabaferdous12** [comment]
Hi Milan @milanmlft , 

I have tried doing this (multiple md files) but looks like we can't see it as we have removed `More` button. 

I was wondering if we could have that back and rename it as `Handbook`?

**Comment by milanmlft** [comment]
## To do

- [x] Create a minimal lesson which contains the L2D handbook contents
	- [x] Need to check whether it's possible to circumvent `sandpaper`'s requirements to have `Questions & Objectives` (and other elements) in an episode.
- [x] Link to this webpage in the header of other lessons, where the `More` button used to be: https://github.com/LearnToDiscover/varnish/pull/29

### ~Alternative~

~In caser the above doesn't work:~

~- [ ] Re-add `More` button; partially revert https://github.com/LearnToDiscover/varnish/pull/20~
~- [ ] Rename `More` to `L2D Handbook`~

**Comment by milanmlft** [comment]
## L2D Handbook lesson

- Lesson repo now up at https://github.com/LearnToDiscover/L2D-Handbook
- It's no problem to remove `Questions and Objectives`, `sandpaper` will give a warning about this but the lesson will still build fine, so you can ignore this
- It's not possible to remove the `instructors/`, `learners/` or `profiles/` directories, they must contain at least 1 (R)markdown file, otherwise `sandpaper` will fail

Regarding the last point, I have stripped down the files as much as possible to the minimal required contents. For `learners/setup.md`, I have replaced the contents with an overview of the handbook's sections (currently just placeholder files), as this is the file shat is shown on the homepage by default.

Of course, feel free to edit any of these files as you wish!

**Comment by DrAdamLee** [comment]
This looks brilliant - thank you so much, @milanmlft! Is there any chance you could add a button to that header bar, next to 'Key Points' and 'Learner Profiles', and call it 'L2D Handbook'? That would be lovely, if you could. Would you like us to create a new issue for this? Thanks so much for your help!
